baseURL = "http://example.org/"
languageCode = "en-us"
title = "who.ldelossa.is"
theme = "hello-friend-ng"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "a.programing.blog."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = ""
  keywords = "linux, technology, systems, networking, programming, golang, software"
  images = [""]

[languages]
  [languages.en]
    title = "who.ldelossa.is"
    subtitle = "a.programming.blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "nc who.ldelossa.is 80"
      logoHomeLink = "/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

# And you can even create generic menu
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

